# 应用配置
app:
  name: "Random Today"
  version: "1.0.0"
  port: 8080
  environment: "development"

# 数据库配置
database:
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "random_today"
    timeout: 10s
    max_pool_size: 100

# 日志配置
logging:
  level: "info"
  format: "json"
  output: "stdout"

# API配置
api:
  prefix: "/api"
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]
    allowed_headers: ["Content-Type", "Authorization"] 